<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <ProjectReference Include="..\Stelliberty.Application\Stelliberty.Application.csproj" />
  </ItemGroup>
  <ItemGroup>
    <InternalsVisibleTo Include="$(AppName)-ui" />
    <InternalsVisibleTo Include="Stelliberty.Tests" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="TextMateSharp" Version="2.0.4" />
    <PackageReference Include="TextMateSharp.Grammars" Version="2.0.4" />
  </ItemGroup>
</Project>
